// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
// import "bootstrap"
import "src/jquery"
import "src/datatables-bs5"

import "custom/sidebar"
import "custom/books_datatable"
import "custom/want_lists_datatable"
import "custom/all_want_lists_datatable"
import "custom/rental_returns_datatable"
import "custom/users_datatable"
import "custom/custom_isbns_datatable"
import "custom/accounts_datatable"
import "custom/tracked_skus_datatable"
import "custom/audits_datatable"
import "custom/thrift_orders_datatable"
import "custom/easy_post_accounts_datatable"
import "custom/reporting_pages_datatable"
import "custom/want_list_items_datatable"
